version: '3.9'

services:
  nginx-acme:
    image: jaimeqian/nginx-acme:latest
    container_name: nginx-acme
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - acmecerts:/acmecerts
      - nginx-conf:/nginx-conf
      - log:/var/log

volumes:
  acmecerts:
  nginx-conf:
  log:


